name: Checks on Pull Requests

on:
  pull_request: {}

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots test --fail-at-end

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dbelyaev/action-checkstyle@master
        with:
          reporter: github-pr-check
          level: info
          checkstyle_config: checkstyle.xml
