name: Build and Publish Snapshot Artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Compiled JAR
          path: |
            target/*.jar
